package com.phonewhisperer.domain.model

/**
 * Represents an automation rule generated by the on-device LLM.
 *
 * Phase 3/4 implementation. An AutomationRule is created when the LLM
 * translates a BehaviorPattern into an actionable automation.
 *
 * Example: "Enable DND every weekday from 9:00 AM to 5:00 PM when at Office"
 */
data class AutomationRule(
    val id: Long = 0,
    val patternId: Long,                // FK to BehaviorPattern
    val ruleName: String,               // "Silence at Work"
    val ruleDescription: String,        // LLM-generated explanation
    val triggerType: TriggerType,
    val triggerValue: String,           // JSON trigger config
    val actionType: ActionType,
    val actionValue: String,            // JSON action config
    val isApproved: Boolean = false,
    val isActive: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
    val lastTriggeredAt: Long? = null,
    val triggerCount: Int = 0
)

enum class TriggerType {
    TIME_BASED,         // Specific time + day of week
    LOCATION_ENTER,     // Enter a geofenced area
    LOCATION_EXIT,      // Exit a geofenced area
    APP_OPEN,           // Specific app launched
    CALENDAR_EVENT,     // Calendar event starting
    COMPOUND            // Multiple conditions (AND/OR)
}

enum class ActionType {
    ENABLE_DND,         // Turn on Do Not Disturb
    DISABLE_DND,        // Turn off Do Not Disturb
    SET_VOLUME,         // Set ringer/media volume
    SET_ALARM,          // Create/modify alarm
    LAUNCH_APP,         // Open specific app
    SEND_NOTIFICATION,  // Show a reminder notification
    COMPOUND            // Multiple actions
}
