package com.phonewhisperer.data.local.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents an automation rule generated by the AI Engine.
 *
 * Phase 3 AI Engine output. Proposed to the user for approval.
 */
@Entity(
    tableName = "automation_rules",
    foreignKeys = [
        ForeignKey(
            entity = BehaviorPatternEntity::class,
            parentColumns = ["id"],
            childColumns = ["pattern_id"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("pattern_id")]
)
data class AutomationRuleEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    @ColumnInfo(name = "pattern_id")
    val patternId: Long,

    @ColumnInfo(name = "name")
    val name: String, // "Work Mute"

    @ColumnInfo(name = "description")
    val description: String, // "Mutes phone on weekdays at 9 AM"

    @ColumnInfo(name = "trigger_type")
    val triggerType: String, // "TIME", "LOCATION"

    @ColumnInfo(name = "trigger_value")
    val triggerValue: String, // "09:00", "Place_1"

    @ColumnInfo(name = "action_type")
    val actionType: String, // "DND", "APP_LAUNCH"

    @ColumnInfo(name = "action_value")
    val actionValue: String, // "SILENT"

    @ColumnInfo(name = "status")
    val status: String // "PENDING", "APPROVED", "REJECTED"
) {
    companion object {
        const val STATUS_PENDING = "PENDING"
        const val STATUS_APPROVED = "APPROVED"
        const val STATUS_REJECTED = "REJECTED"
    }
}
